// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByL3_NpnOgUZC9Kqfl4zlo-iA-U0o63S0',
    appId: '1:984002542282:android:26bb1dd9079471f4e05233',
    messagingSenderId: '984002542282',
    projectId: 'social-app-8905d',
    storageBucket: 'social-app-8905d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbUlp4VpYSfoVqqPl8PDUQBMn3ByVnlr8',
    appId: '1:984002542282:ios:5411906d416d15ebe05233',
    messagingSenderId: '984002542282',
    projectId: 'social-app-8905d',
    storageBucket: 'social-app-8905d.appspot.com',
    androidClientId: '984002542282-4e3cvqp647uu54atf194ro5becdaqdf8.apps.googleusercontent.com',
    iosClientId: '984002542282-qc0e0bi82gc828nmg0t1prm4fh7te4tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxWeather',
  );
}
